import { Resend } from 'resend'
import EmailLog from "@/models/EmailLog"
import { connectDB } from "@/lib/mongodb"

// Initialize Resend safely
const getResendClient = () => {
  const apiKey = process.env.RESEND_API_KEY
  if (!apiKey) {
    console.log("\n--- MOCK EMAIL MODE (RESEND_API_KEY missing) ---")
    return null
  }
  return new Resend(apiKey)
}

/**
 * MAIN FUNCTION: send restock email using Resend SDK
 */
export async function sendRestockEmail(payload) {
  await connectDB()

  const {
    productName,
    sku,
    supplierEmail,
    supplierName,
    currentStock,
    threshold,
    suggestedQuantity,
    imageUrl,
    orgName,
    managerName,
    managerPhone,
    productId,
    supplierId,
    organizationId,
  } = payload

  if (!supplierEmail) {
    return { sent: false, error: "No supplier email provided" }
  }

  const isOutOfStock = currentStock === 0
  const urgencyLabel = isOutOfStock ? "CRITICAL: OUT OF STOCK" : "LOW STOCK WARNING"
  const urgencyColor = isOutOfStock ? "#EF4444" : "#F59E0B"

  const html = `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #F8FAFC; padding: 40px 10px; color: #0F172A;">
      <div style="max-width: 600px; margin: 0 auto; bg-color: #FFFFFF; background: #FFFFFF; border-radius: 16px; border: 1px solid #E2E8F0; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);">
        
        <!-- Header -->
        <div style="background-color: #0F172A; padding: 24px; text-align: center;">
          <h2 style="color: #FFFFFF; margin: 0; font-size: 20px; font-weight: 800; tracking-tight">Purchase Restock Order</h2>
          <p style="color: #94A3B8; margin: 4px 0 0 0; font-size: 13px;">Generated by ${orgName || 'StockSense IMS'}</p>
        </div>

        <!-- Body -->
        <div style="padding: 32px 24px;">
          <p style="font-size: 15px; line-height: 1.5; color: #334155; margin-top: 0;">Dear ${supplierName || "Supplier Partner"},</p>
          <p style="font-size: 15px; line-height: 1.5; color: #334155;">This is an automated purchase restock request. Our inventory levels for the product listed below have dropped below their minimum safety limits. Please review the order parameters details:</p>

          <!-- Urgency Badge -->
          <div style="margin: 20px 0; text-align: left;">
            <span style="background-color: ${urgencyColor}15; color: ${urgencyColor}; border: 1px solid ${urgencyColor}30; padding: 6px 12px; border-radius: 99px; font-size: 11px; font-weight: 700; letter-spacing: 0.05em; text-transform: uppercase;">
              ${urgencyLabel}
            </span>
          </div>

          <!-- Product Details Card -->
          <div style="background-color: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 12px; padding: 20px; margin-bottom: 24px; display: flex; align-items: center; gap: 16px;">
            ${imageUrl ? `<img src="${imageUrl}" alt="${productName}" style="width: 80px; height: 80px; object-fit: cover; border-radius: 8px; border: 1px solid #E2E8F0; float: left; margin-right: 16px;" />` : ""}
            <div style="overflow: hidden;">
              <h3 style="margin: 0 0 4px 0; font-size: 16px; font-weight: 700; color: #0F172A;">${productName}</h3>
              <p style="margin: 0; font-family: monospace; font-size: 12px; color: #64748B;">SKU: ${sku}</p>
            </div>
            <div style="clear: both;"></div>
          </div>

          <!-- Order Summary Table -->
          <table style="width: 100%; border-collapse: collapse; margin-bottom: 24px; font-size: 14px;">
            <thead>
              <tr style="border-bottom: 2px solid #E2E8F0; text-align: left;">
                <th style="padding: 10px 0; color: #64748B; font-weight: 600;">Inventory Parameter</th>
                <th style="padding: 10px 0; text-align: right; color: #64748B; font-weight: 600;">Status Level</th>
              </tr>
            </thead>
            <tbody>
              <tr style="border-bottom: 1px solid #F1F5F9;">
                <td style="padding: 12px 0; color: #475569;">Current Stock</td>
                <td style="padding: 12px 0; text-align: right; font-weight: 700; color: ${isOutOfStock ? '#EF4444' : '#0F172A'};">${currentStock} units</td>
              </tr>
              <tr style="border-bottom: 1px solid #F1F5F9;">
                <td style="padding: 12px 0; color: #475569;">Minimum Threshold Limit</td>
                <td style="padding: 12px 0; text-align: right; color: #0F172A;">${threshold} units</td>
              </tr>
              <tr style="border-bottom: 1px solid #F1F5F9;">
                <td style="padding: 12px 0; color: #0F172A; font-weight: 600;">Suggested Reorder Quantity</td>
                <td style="padding: 12px 0; text-align: right; font-weight: 800; color: #2563EB; font-size: 16px;">${suggestedQuantity} units</td>
              </tr>
            </tbody>
          </table>

          <p style="font-size: 14px; line-height: 1.5; color: #475569;">Please reply directly to this email to confirm availability, confirm total pricing, and specify the estimated shipment date.</p>
          
          <!-- Manager Signature -->
          <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #E2E8F0; font-size: 13px; color: #64748B;">
            <p style="margin: 0; font-weight: 600; color: #334155;">${managerName || 'Inventory Operations Manager'}</p>
            <p style="margin: 2px 0 0 0;">${orgName || 'StockSense IMS'}</p>
            ${managerPhone ? `<p style="margin: 2px 0 0 0;">Contact: ${managerPhone}</p>` : ""}
          </div>
        </div>

        <!-- Footer -->
        <div style="background-color: #F8FAFC; padding: 20px; text-align: center; border-top: 1px solid #E2E8F0; font-size: 11px; color: #94A3B8;">
          This restock order request is automated and trackable. Generated by StockSense IMS.
        </div>

      </div>
    </div>
  `

  const from = `"${orgName || 'StockSense IMS'}" <${process.env.EMAIL_FROM || "onboarding@resend.dev"}>`
  const subject = `📦 Purchase Restock Request - ${productName}`

  const resend = getResendClient()

  if (!resend) {
    // MOCK MODE
    console.log("\n--- [MOCK MAIL ALERT - RESTOCK REQUEST] ---")
    console.log(`From: ${from}`)
    console.log(`To: ${supplierEmail}`)
    console.log(`Subject: ${subject}`)
    console.log("-------------------------\n")

    await EmailLog.create({
      type: "restock_request",
      productId,
      productName,
      supplierId,
      supplierEmail,
      quantitySuggested: suggestedQuantity,
      status: "sent",
      error: "",
      organizationId,
    })
    return { sent: true, mock: true }
  }

  try {
    const response = await resend.emails.send({
      from,
      to: supplierEmail,
      subject,
      html,
    })

    if (response.error) {
      throw new Error(response.error.message)
    }

    // LOG SUCCESS
    await EmailLog.create({
      type: "restock_request",
      productId,
      productName,
      supplierId,
      supplierEmail,
      quantitySuggested: suggestedQuantity,
      status: "sent",
      error: "",
      organizationId,
    })

    return { sent: true, id: response.data?.id }
  } catch (err) {
    console.error("Email Error:", err)

    await EmailLog.create({
      type: "restock_request",
      productId,
      productName,
      supplierId,
      supplierEmail,
      quantitySuggested: suggestedQuantity,
      status: "failed",
      error: err.message,
      organizationId,
    })

    return { sent: false, error: err.message }
  }
}

/**
 * Sends a single restock order request containing all low stock items from a specific supplier.
 */
export async function sendSupplierGroupedRestockEmail({
  supplier,
  products,
  orgName,
  managerName,
  organizationId,
}) {
  await connectDB()

  if (!supplier?.email) {
    return { sent: false, error: "No supplier email provided" }
  }

  const hasOutOfStock = products.some((p) => p.stock === 0)
  const urgencyLabel = hasOutOfStock ? "CRITICAL: OUT OF STOCK" : "LOW STOCK WARNING"
  const urgencyColor = hasOutOfStock ? "#EF4444" : "#F59E0B"

  const productsTableHtml = products.map((p) => {
    const soq = (p.threshold * 2) - p.stock
    const suggestedQuantity = soq > 0 ? soq : p.threshold
    return `
      <tr style="border-bottom: 1px solid #F1F5F9;">
        <td style="padding: 12px 8px; color: #0F172A; text-align: left;">
          <div style="font-weight: 700; font-size: 14px;">${p.name}</div>
          <div style="font-size: 11px; color: #64748B; font-family: monospace;">SKU: ${p.sku}</div>
        </td>
        <td style="padding: 12px 8px; text-align: center; color: ${p.stock === 0 ? '#EF4444' : '#475569'}; font-weight: bold;">
          ${p.stock} units
        </td>
        <td style="padding: 12px 8px; text-align: center; color: #475569;">
          ${p.threshold} units
        </td>
        <td style="padding: 12px 8px; text-align: right; font-weight: 800; color: #2563EB; font-size: 15px;">
          ${suggestedQuantity} units
        </td>
      </tr>
    `
  }).join('')

  const html = `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #F8FAFC; padding: 40px 10px; color: #0F172A;">
      <div style="max-width: 650px; margin: 0 auto; bg-color: #FFFFFF; background: #FFFFFF; border-radius: 16px; border: 1px solid #E2E8F0; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);">
        
        <!-- Header -->
        <div style="background-color: #0F172A; padding: 24px; text-align: center;">
          <h2 style="color: #FFFFFF; margin: 0; font-size: 20px; font-weight: 800; tracking-tight">Purchase Restock Order</h2>
          <p style="color: #94A3B8; margin: 4px 0 0 0; font-size: 13px;">Generated by ${orgName || 'StockSense IMS'}</p>
        </div>

        <!-- Body -->
        <div style="padding: 32px 24px;">
          <p style="font-size: 15px; line-height: 1.5; color: #334155; margin-top: 0;">Dear Supplier Partner,</p>
          <p style="font-size: 15px; line-height: 1.5; color: #334155;">This is an automated purchase restock request. Our inventory levels for the products listed below have dropped below their minimum safety limits. Please review the order parameters details:</p>

          <!-- Urgency Badge -->
          <div style="margin: 20px 0; text-align: left;">
            <span style="background-color: ${urgencyColor}15; color: ${urgencyColor}; border: 1px solid ${urgencyColor}30; padding: 6px 12px; border-radius: 99px; font-size: 11px; font-weight: 700; letter-spacing: 0.05em; text-transform: uppercase;">
              ${urgencyLabel}
            </span>
          </div>

          <!-- Order Summary Table -->
          <table style="width: 100%; border-collapse: collapse; margin-bottom: 24px; font-size: 14px;">
            <thead>
              <tr style="border-bottom: 2px solid #E2E8F0; text-align: left; background-color: #F8FAFC;">
                <th style="padding: 10px 8px; color: #64748B; font-weight: 600; text-align: left;">Product Details</th>
                <th style="padding: 10px 8px; text-align: center; color: #64748B; font-weight: 600;">Current Stock</th>
                <th style="padding: 10px 8px; text-align: center; color: #64748B; font-weight: 600;">Safety Threshold</th>
                <th style="padding: 10px 8px; text-align: right; color: #64748B; font-weight: 600;">Suggested Quantity</th>
              </tr>
            </thead>
            <tbody>
              ${productsTableHtml}
            </tbody>
          </table>

          <p style="font-size: 14px; line-height: 1.5; color: #475569;">Please reply directly to this email to confirm availability, confirm total pricing, and specify the estimated shipment date.</p>
          
          <!-- Manager Signature -->
          <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #E2E8F0; font-size: 13px; color: #64748B;">
            <p style="margin: 0; font-weight: 600; color: #334155;">${managerName || 'Inventory Operations Manager'}</p>
            <p style="margin: 2px 0 0 0;">${orgName || 'StockSense IMS'}</p>
          </div>
        </div>

        <!-- Footer -->
        <div style="background-color: #F8FAFC; padding: 20px; text-align: center; border-top: 1px solid #E2E8F0; font-size: 11px; color: #94A3B8;">
          This restock order request is automated and trackable. Generated by StockSense IMS.
        </div>

      </div>
    </div>
  `

  const from = `"${orgName || 'StockSense IMS'}" <${process.env.EMAIL_FROM || "onboarding@resend.dev"}>`
  const subject = `📦 Purchase Restock Request - Multiple Items (${orgName || 'StockSense IMS'})`

  const resend = getResendClient()
  let sentStatus = 'failed'
  let emailError = ''
  let id = null

  if (!resend) {
    console.log("\n--- [MOCK MAIL ALERT - GROUPED RESTOCK] ---")
    console.log(`From: ${from}`)
    console.log(`To: ${supplier.email}`)
    console.log(`Subject: ${subject}`)
    console.log("-------------------------\n")
    sentStatus = 'sent'
  } else {
    try {
      const response = await resend.emails.send({
        from,
        to: supplier.email,
        subject,
        html,
      })

      if (response.error) {
        throw new Error(response.error.message)
      }

      sentStatus = 'sent'
      id = response.data?.id
    } catch (err) {
      console.error("Grouped Email Error:", err)
      emailError = err.message
    }
  }

  // Create individual EmailLog records for EACH product in the email
  const logPromises = products.map((p) => {
    const soq = (p.threshold * 2) - p.stock
    const suggestedQuantity = soq > 0 ? soq : p.threshold
    return EmailLog.create({
      type: "restock_request",
      productId: p._id,
      productName: p.name,
      supplierId: supplier._id,
      supplierEmail: supplier.email,
      quantitySuggested: suggestedQuantity,
      status: sentStatus,
      error: emailError,
      organizationId,
    })
  })

  await Promise.all(logPromises)

  return { sent: sentStatus === 'sent', error: emailError, id }
}

/**
 * Sends a low stock alert email to the administrator listing all affected items.
 */
export async function sendLowStockAlert(products) {
  await connectDB()
  const emailFrom = process.env.EMAIL_FROM

  const productsTableHtml = products.map((p) => `
    <tr style="border-bottom: 1px solid #F1F5F9;">
      <td style="padding: 12px 8px; color: #0F172A; text-align: left;">
        <div style="font-weight: 700; font-size: 14px;">${p.name}</div>
        <div style="font-size: 11px; color: #64748B; font-family: monospace;">SKU: ${p.sku}</div>
      </td>
      <td style="padding: 12px 8px; text-align: center; color: #EF4444; font-weight: bold;">
        ${p.stock} units
      </td>
      <td style="padding: 12px 8px; text-align: center; color: #475569;">
        ${p.threshold} units
      </td>
    </tr>
  `).join('')

  const html = `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #F8FAFC; padding: 40px 10px; color: #0F172A;">
      <div style="max-width: 600px; margin: 0 auto; bg-color: #FFFFFF; background: #FFFFFF; border-radius: 16px; border: 1px solid #E2E8F0; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);">
        
        <!-- Header -->
        <div style="background-color: #0F172A; padding: 24px; text-align: center;">
          <h2 style="color: #FFFFFF; margin: 0; font-size: 20px; font-weight: 800; tracking-tight">⚠️ Low Stock Alert</h2>
          <p style="color: #94A3B8; margin: 4px 0 0 0; font-size: 13px;">StockSense Inventory Warning</p>
        </div>

        <!-- Body -->
        <div style="padding: 32px 24px;">
          <p style="font-size: 15px; line-height: 1.5; color: #334155; margin-top: 0;">Hello Administrator,</p>
          <p style="font-size: 15px; line-height: 1.5; color: #334155;">The following products in your inventory have dropped below their minimum safety thresholds. Please review and coordinate restocks:</p>

          <!-- Order Summary Table -->
          <table style="width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 14px;">
            <thead>
              <tr style="border-bottom: 2px solid #E2E8F0; text-align: left; background-color: #F8FAFC;">
                <th style="padding: 10px 8px; color: #64748B; font-weight: 600; text-align: left;">Product</th>
                <th style="padding: 10px 8px; text-align: center; color: #64748B; font-weight: 600;">Current Stock</th>
                <th style="padding: 10px 8px; text-align: center; color: #64748B; font-weight: 600;">Safety Threshold</th>
              </tr>
            </thead>
            <tbody>
              ${productsTableHtml}
            </tbody>
          </table>

          <div style="margin-top: 30px; text-align: center;">
            <a href="${process.env.NEXTAUTH_URL || 'http://localhost:3000'}/products" style="background-color: #FF4D6D; color: #FFFFFF; padding: 12px 24px; text-decoration: none; border-radius: 8px; font-weight: 700; display: inline-block; box-shadow: 0 4px 6px -1px rgba(255, 77, 109, 0.2);">
              Manage Catalog
            </a>
          </div>
        </div>

        <!-- Footer -->
        <div style="background-color: #F8FAFC; padding: 20px; text-align: center; border-top: 1px solid #E2E8F0; font-size: 11px; color: #94A3B8;">
          StockSense IMS • Real-time inventory intelligence
        </div>

      </div>
    </div>
  `

  const from = `"StockSense IMS Alerts" <${emailFrom || "onboarding@resend.dev"}>`
  const to = emailFrom || "admin@stocksense.app"
  const subject = "⚠️ Low Stock Alert — Action Required"

  const resend = getResendClient()

  if (!resend) {
    console.log("\n--- [MOCK MAIL ALERT - LOW STOCK] ---")
    console.log(`From: ${from}`)
    console.log(`To: ${to}`)
    console.log(`Subject: ${subject}`)
    console.log("-------------------------\n")
    return { mock: true, sent: true }
  }

  try {
    const response = await resend.emails.send({
      from,
      to,
      subject,
      html,
    })

    if (response.error) {
      throw new Error(response.error.message)
    }

    return { sent: true, id: response.data?.id }
  } catch (err) {
    console.error("Low Stock Alert Email Error:", err)
    return { sent: false, error: err.message }
  }
}